name: .NET CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['5.0.x']
    name: .NET ${{ matrix.dotnet }} test
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Clean
        run: dotnet clean
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter "FullyQualifiedName!=PurpleSofa.Tests.TestServer.TestForever" --collect:"XPlat Code Coverage"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}