name: .NET CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    name: .NET test
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
      - name: Clean
        run: dotnet clean
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --filter "FullyQualifiedName!=PurpleSofa.Tests.TestServer.TestForever" --collect:"XPlat Code Coverage"
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}